[package]
name = "raiz-attestation-registry"
version = "1.0.0"
edition = "2021"
authors = ["Open Hub TecNM - Instituto Tecnológico de Tlaxiaco"]
license = "MIT"
description = "Universal RWA Attestation Registry for Soroban & Stellar"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
